language: node_js

node_js:
  - "18"

jobs:
  include:
    - stage: deploy dev
      if: branch = dev
      script: echo "stage de deploy dev"
    - stage: deploy main
      if: branch = main
      script: echo "stage de deploy main"
    